name: "Setup Virtual Env"
description: Sets up virtualenv + React; compiles protobuf

inputs:
  use_cached_venv:
    description: "Use Cached Virtual Env"
    default: "true"

# There is an altered copy of these steps inlined in the python_min_deps
# workflow. If you make changes to this action, apply them there too if appropriate.
runs:
  using: composite
  steps:
    - name: Enable and Prepare Latest Yarn
      run: |
        corepack enable
        corepack prepare yarn@4.5.3 --activate
      shell: bash
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"
        cache-dependency-path: "**/yarn.lock"
    - name: Initialize React
      run: |
        # Create the cache directory if it does not exist.
        mkdir -p $(yarn cache dir)
        make react-init
      shell: bash
    # We require protoc >= 3.20, but Ubuntu 22.04 - the OS that these Github
    # Actions are running as of 2024.06.04 - doesn't have recent versions
    # of protoc in its package repository. To work around this, we
    # install the latest version from the protobuf release page.
    - name: Install `protoc` binary
      run: |
        PROTOC_VERSION=26.1
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
        sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local 'include/*'
        sudo ln -s /usr/local/bin/protoc /usr/bin/protoc
        # Print out your System's protoc version:
        protoc --version
      shell: bash
    # Combine hashes of the Python interpreter, Pipfile, and today's
    # date into a file whose hash will key the Python virtualenv.
    #
    # This means that our virtualenv cache will expire each day. We do
    # this because we are not using a lockfile to pin dependencies -
    # instead, each time Github Actions rebuilds the virtualenv, it uses the
    # latest compatible version of each dependency (which mirrors what
    # happens when a user installs Streamlit locally). So we expire our
    # virtualenv cache daily to prevent it from getting far out of sync
    # with what a fresh Streamlit installation would look like.
    - if: inputs.use_cached_venv == 'true'
      name: Create Python environment cache key
      run: |
        md5sum $(which python) > $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/dev-requirements.txt >> $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/test-requirements.txt >> $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/setup.py >> $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum Makefile >> $GITHUB_WORKSPACE/python_cache_key.md5
        date +%F >> $GITHUB_WORKSPACE/python_cache_key.md5
      shell: bash
    - if: inputs.use_cached_venv == 'true'
      name: Restore virtualenv from cache
      id: cache-virtualenv
      uses: actions/cache@v4
      with:
        path: venv
        key: v1-python-venv-${{ hashFiles('**/python_cache_key.md5') }}
    - if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      name: Create Virtual Env
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install uv
        make python-init
      shell: bash
    - name: Activate virtualenv
      run: echo "${{ github.workspace }}/venv/bin" >> $GITHUB_PATH
      shell: bash
    - name: Show environment info
      run: |
        echo "Show environment info"
        echo "Python version:"
        python --version
        echo "Installed dependencies:"
        python -m pip list
      shell: bash
    - name: Generate Protobufs
      run: make protobuf
      shell: bash
